# -*- coding: utf-8 -*-
"""PasswordChecker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eXtNw0m2moA2GadqZDPTzAy0L1_PD4a1
"""

import re

def check_password_strength(password):
    score = 0
    suggestion = []

    # length check
    if len(password) >= 8:
        score += 1
    else:
        suggestion.append("Use at least 8 characters")

    # uppercase check
    if re.search(r"[A-Z]", password):
        score += 1
    else:
        suggestion.append("Add uppercase letters")

    # lowercase check
    if re.search(r"[a-z]", password):
        score += 1
    else:
        suggestion.append("Add lowercase letters")

    # digit check
    if re.search(r"\d", password):
        score += 1
    else:
        suggestion.append("Include numbers")

    # special character check
    if re.search(r"[!@#$%^&*()]", password):
        score += 1
    else:
        suggestion.append("Add special characters")

    # strength result
    if score <= 2:
        strength = "Weak"
    elif score <= 4:
        strength = "Medium"
    else:
        strength = "Strong"

    return strength, suggestion


# main program
password = input("Enter your password: ")

strength, suggestion = check_password_strength(password)

print("\nPassword Strength:", strength)

if suggestion:
    print("Suggestions to improve:")
    for n in suggestion:
        print("-", n)
else:
    print("Your password is secure!")

